- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get DNS Server Group Object
      cisco.fmcansible.fmc_configuration:
        operation: "getAllDNSServerGroupObject"
        path_params:
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
        filters:
          name: "{{ delete_dnservergroupobject_name }}"
        register_as: dnsobject

    - name: Delete FQDN network for Cisco DevNet
      cisco.fmcansible.fmc_configuration:
        operation: deleteDNSServerGroupObject
        path_params:
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
          objectId: "{{ dnsobject[0].id }}"
