- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Execute 'getAllPrefilterPolicy' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllPrefilterPolicy"
        path_params:
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
        filters:
          name: "{{ delete_prefilterpolicy_name }}"
        register_as: prefilter

    - name: Delete Prefilter Policy
      cisco.fmcansible.fmc_configuration:
        operation: deletePrefilterPolicy
        path_params:
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
          objectId: "{{ prefilter[0].id }}"
