- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get FTD Nat Policy
      cisco.fmcansible.fmc_configuration:
        operation: "getAllFTDNatPolicy"
        path_params:
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
        filters:
          name: "{{ delete_natpolicy_name }}"
        register_as: natpolicy

    - name: Delete FTD Nat Policy
      cisco.fmcansible.fmc_configuration:
        operation: "deleteFTDNatPolicy"
        path_params:
          objectId: "{{ natpolicy[0].id }}"
          domainUUID: "{{ ansible_facts.fmc.domains[0].uuid }}"
